#parameters
#

RegParameters:
        lambda: 0.001

OptParameters:
        SGDParameters:
                iterations: 90
                miniBatchFraction: 0.5
                stepSize: 0.001
                seed: 13
                convergenceTol: 0.0001
        GDParameters:
                iterations: 90
                miniBatchFraction: 1.0
                stepSize: 0.001
                seed: 13
                convergenceTol: 0.0001
